/*
 * Backend Test API
 *
 * Service for receiving trades from the outside world
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Submitted trade details
type TradeSubmitted struct {
	// Unique ID for this trade that you defined.
	ClientTradeId string `json:"client_trade_id,omitempty"`
	// Unique ID for this trade
	TradeId string `json:"trade_id,omitempty"`
}
