/*
 * Backend Test API
 *
 * Service for receiving trades from the outside world
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Base trade details; common amongst all trade types.
type Trade struct {
	// Unique ID for this trade that you define.
	ClientTradeId string `json:"client_trade_id"`
	// Trade date for the trade in YYYYMMDD format
	Date int32 `json:"date"`
	// The quantity of the trade
	Quantity string `json:"quantity"`
	// The price of the trade
	Price string `json:"price"`
	// Ticker (Unique Identifier) traded
	Ticker string `json:"ticker"`
}
